### ISSUE TITLE
Warning/Error: Left shift of negative value when executing ASR instruction

### ISSUE THREAD

**Issue by ScottEgerton** [andresag01/thumb-sim#1]
When compiling with gcc 7.3.0, two warnings are thrown [shift-negative-value]. Due to the fact that -Werror is enabled, this fails to compile for me.

These come from line [311](https://github.com/andresag01/thumb-sim/blob/master/library/alu.cpp#L311) and [354](https://github.com/andresag01/thumb-sim/blob/master/library/alu.cpp#L354) in the file library/alu.cpp which reads:

```cpp
311:    dres = dres | (~0 << (BITS_PER_WORD - im));
```
and
```cpp
354:    dres = dres | (~0 << (BITS_PER_WORD - drm));
```

I think the warning is that `~0` is negative and a left shift is being performed on this.

As a workaround I have replaced these with the following code and I am happy to open a pull request, however I don't know if this is what was intended.
```cpp
354:    dres |= (static_cast<uint32_t>(~0) << (BITS_PER_WORD - drm));
```

**Comment by andresag01** [comment]
@ScottEgerton: Thanks for reporting this issue. I pushed [this](https://github.com/andresag01/thumb-sim/commit/f0a2e9798fa257c57aa395935093ab734c16bb31) patch to fix the problem. While working on that, I also found that there was another compilation warning due to a missing `break` statement in some debug code, so I fixed that as well.

The changes are already in the master branch, so I think this issue can be closed. However, please feel free to reopen it if you do not agree.
